// Turn the built bundle into a C array the firmware compiles in.
//
// This is not a return to what v1.11.0 removed. What went then was hand-written
// JavaScript inside C++ raw string literals - no bundler, no packages, no source
// maps, and nothing in the build that ever parsed it, so a typo shipped and surfaced
// as a dead dashboard in a car. All of that stays gone: this reads the output of the
// ordinary Vite build, after the ordinary Vitest suite, and turns the finished
// gzipped bytes into a byte array. Nothing about how the frontend is written,
// bundled or tested changes.
//
// What it buys is one artifact. A stranger who flashes the board through
// docs/flash/ currently gets the built-in fallback page - speed, rpm, coolant,
// battery - and has to find web/deploy.sh, a laptop and the board's Wi-Fi before
// seeing the actual dashboard. Compiled in, flashing is the whole install.
//
// The cost is a reflash to change a line of CSS, which is exactly what made the old
// arrangement painful. So the compiled-in copy is the DEFAULT, not the only one: a
// bundle uploaded to LittleFS still wins, and web/deploy.sh still gives a
// no-reflash edit loop. See uiTrySend() for the order.
//
// That also strengthens the property the split was protecting. "Deploying cannot
// brick it" used to mean falling back to a four-value stub; now a failed or absent
// deploy falls back to the last dashboard that was compiled in.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const gz = join(here, '..', 'dist', 'index.html.gz');
const out = join(here, '..', '..', 'firmware', 'Obdurate', 'ui_bundle.h');

if (!existsSync(gz)) {
  console.error('embed: no dist/index.html.gz - run the build first');
  process.exit(1);
}

const bytes = readFileSync(gz);
const version = JSON.parse(
  readFileSync(join(here, '..', 'package.json'), 'utf8'),
).version;

// PROGMEM and a plain array. The firmware streams it with Content-Encoding: gzip,
// exactly as it serves the LittleFS copy, so the two paths differ only in where the
// bytes come from.
const lines = [];
for (let i = 0; i < bytes.length; i += 16) {
  const row = [...bytes.subarray(i, i + 16)].map((b) => '0x' + b.toString(16).padStart(2, '0'));
  lines.push('  ' + row.join(', ') + ',');
}

writeFileSync(out, `#pragma once
#include <Arduino.h>

// GENERATED by web/scripts/embed.mjs - do not edit.
//
// The built frontend, gzipped, compiled into flash so that flashing the board is the
// whole install. A bundle uploaded to LittleFS overrides this one; see ui_fs.h.
//
// Source: web/dist/index.html.gz
// Frontend version: ${version}
// Size: ${bytes.length} bytes gzipped

#define UI_BUNDLE_VERSION "${version}"

static const uint8_t UI_BUNDLE_GZ[] PROGMEM = {
${lines.join('\n')}
};
static const size_t UI_BUNDLE_GZ_LEN = ${bytes.length};
`);

console.log(`  embedded ${bytes.length} B gzipped as firmware/Obdurate/ui_bundle.h`);
