#!/usr/bin/env python3
"""Pull named functions verbatim out of NexonOBD.ino.

The tests compile the real function bodies rather than a copy of them, so a change
to the sketch that breaks the ISO-TP contract fails the tests instead of quietly
leaving a stale duplicate passing.
"""
import re
import sys
import pathlib

WANT = ["hexNib", "canIsoTp", "bleIsoTp", "obdIsoTp",
        "pidLen", "applyPid", "mode01Walk", "pollBatch", "sampleBatchPids", "sampleStaleMs", "sampleMerge", "pickBackoff",
        "monMaskMids", "monParse", "tripIntegrate"]

# File-scope data the extracted functions reference. Pulled verbatim so the tests
# exercise the real PID lists rather than a copy that can drift.
WANT_VARS = ["PID_B1", "PID_B2", "PID_B3", "PID_B4", "SAMPLE_ORDER",
             "SAMPLE_BATCHES",
             "SAMPLE_STALE_MIN_MS", "SAMPLE_STALE_MAX_MS",
             "PICK_MIN_MS", "PICK_MAX_MS",
             "g_tripKm", "g_tripL", "tripIntAt", "TRIP_INT_MAX_MS"]


def extract(src: str, name: str) -> str:
    # Anchor on the definition (always `static <type> name(`), never a call site
    # or a mention in a comment.
    m = re.search(r"^static\s[^\n]*\b" + re.escape(name) + r"\s*\(", src, re.M)
    if not m:
        sys.exit(f"extract: no definition of {name}() found")
    i = src.index("{", m.end() - 1)
    depth = 0
    while True:
        if src[i] == "{":
            depth += 1
        elif src[i] == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    return src[m.start():i + 1]


def extract_var(src: str, name: str) -> str:
    # A leading storage attribute is optional, and so is the initialiser: a variable
    # that lives in RTC slow memory is written `RTC_DATA_ATTR static float g_tripKm;`
    # with no `= 0.0f`, because the whole point is that a deep-sleep wake must not
    # reinitialise it. shims.h defines RTC_DATA_ATTR away, so the extracted line
    # still compiles on the host as the plain zero-initialised static it needs to be.
    m = re.search(r"^(?:[A-Z_][A-Z0-9_]*\s+)?static\s[^\n]*\b" + re.escape(name) +
                  r"\s*(?:\[[^\]]*\])?\s*(?:=[^;]*)?;", src, re.M)
    if not m:
        sys.exit(f"extract: no definition of {name} found")
    return m.group(0)


def main() -> None:
    ino = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
    out = ["// Generated by extract.py - do not edit. Source: NexonOBD.ino\n"]
    for name in WANT_VARS:
        out.append(extract_var(ino, name))
        out.append("\n")
    out.append("\n")
    for name in WANT:
        out.append(extract(ino, name))
        out.append("\n\n")
    pathlib.Path(sys.argv[2]).write_text("".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
